# Generated by Django 5.1.3 on 2024-11-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerclass_rename_name_card_card_name_addtodeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeekerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='addtodeck',
            name='player_class',
        ),
        migrations.AddField(
            model_name='addtodeck',
            name='hider_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hiderclass'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.profile')),
                ('hider_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hiderclass')),
                ('seeker_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.seekerclass')),
            ],
        ),
        migrations.AddField(
            model_name='addtodeck',
            name='seeker_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.seekerclass'),
        ),
        migrations.DeleteModel(
            name='PlayerClass',
        ),
    ]
