# Generated by Django 5.1.3 on 2024-11-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hiderclass_seekerclass_remove_addtodeck_player_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtodeck',
            name='hider_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.hiderclass'),
        ),
        migrations.AlterField(
            model_name='addtodeck',
            name='seeker_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.seekerclass'),
        ),
    ]
