# Generated by Django 5.1.3 on 2024-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_hiderclass_hider_rename_seekerclass_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='hider',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
