# Generated by Django 5.1.3 on 2024-12-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.profile')),
            ],
        ),
    ]
