# Generated by Django 5.1.3 on 2024-12-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_favoritecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.card'),
        ),
        migrations.DeleteModel(
            name='FavoriteCard',
        ),
    ]
