# Generated by Django 5.1.3 on 2024-12-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_uploadcard_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcard',
            name='image_file',
        ),
    ]
