# Generated by Django 5.1.3 on 2024-12-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_uploadcard_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
